# Generated by Django 3.0.6 on 2020-06-07 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('time_spend', models.IntegerField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_columns', models.IntegerField()),
                ('number_of_rows', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('seans_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Film')),
                ('seans_sall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Sall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=240)),
                ('row', models.CharField(max_length=2)),
                ('column', models.IntegerField()),
                ('seans_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Seans')),
            ],
        ),
    ]
